name: core
description: BravosTix Core module
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.0
  dartz: ^0.10.0-nullsafety.2
  equatable: ^2.0.3
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/images/
     
  fonts:
    - family: Circular Std
      fonts:
        - asset: assets/fonts/Circular-Std-Book.ttf
        - asset: assets/fonts/Circular-Std-Book-Italic.ttf
          style: italic
        - asset: assets/fonts/Circular-Std-Bold.ttf
          weight: 700
        - asset: assets/fonts/Circular-Std-Bold-Italic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Circular-Std-Medium.ttf
          weight: 500
        - asset: assets/fonts/Circular-Std-Medium.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Circular-Std-Black.ttf
          weight: 600
        - asset: assets/fonts/Circular-Std-Black-Italic.ttf
          weight: 600
          style: italic
